services:
  chatbot:
    build: .
    container_name: oneeloom_bot
    ports:
      - "8000:8000"
    environment:
      NODE_ENV: "production"
      PORT: "${PORT}"
      BOT_API_TOKEN: "${BOT_API_TOKEN}"
      BOT_CHAT_ID: "${BOT_CHAT_ID}"
